# Generated by Django 4.2.5 on 2023-10-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_course_module_category_remove_course_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/product'),
        ),
    ]
